### ISSUE TITLE
Add more file extensions

### ISSUE THREAD

**Issue by bitm0de** [sentry07/vscode-crestron-splus#1]
https://github.com/sentry07/vscode-crestron-splus/blob/c83ea8e18c399c917ac8fd522c1fb63918f46b96/syntaxes/crestron-splus.tmLanguage.json#L3

I think this should include the "csp" and "csl" file extensions just to be more complete. Both are the Crestron version of the User file extensions.

**Comment by sentry07** [comment]
Fixed, will update codebase with next commit.
