### ISSUE TITLE
Compile Error: X86 unknown cmdlet, function, script file, or operable program. 

### ISSUE THREAD

**Issue by CsVance82** [sentry07/vscode-crestron-splus#15]
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:19
+ C:\Program Files (x86)\Crestron\SIMPL\SPlusCC.exe \rebuild c:\Users\c ...
+                   ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Getting this when compiling.  VS Code version: 
 
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by CsVance82** [comment]
I can compile with mwgustin's S+ extension.

**Comment by CsVance82** [comment]
resolved: do not know how, but I created a task that the compile command was referencing.  Upon deleting the task.json the compiling worked.

**Comment by sentry07** [comment]
Interesting. Thanks for reporting the fix. I'm not sure how I would have diagnosed that.
