### ISSUE TITLE
X86 Issue

### ISSUE THREAD

**Issue by Spoons99205** [sentry07/vscode-crestron-splus#23]
<img width="1220" alt="Capture" src="https://user-images.githubusercontent.com/52833691/160633324-e89e6e66-2c50-4628-93d3-c4ad98fc6984.PNG">

Hello,

Can you explain this issue, we are seeing this on multiple PC's?

**Comment by sentry07** [comment]
That looks like a PowerShell error message. The build commands in the extension specifically use cmd.exe to make the build calls. Have you replaced cmd.exe with pwsh.exe or something? What Windows version are you on? Need more information.

**Comment by sentry07** [comment]
I see on Reddit that you fixed this by deleting the tasks.json file. Closing the issue.
