### ISSUE TITLE
ctrl + shift + B dosen't have a default build task

### ISSUE THREAD

**Issue by chuget** [sentry07/vscode-crestron-splus#24]
I have recently installed your extension and it won't compile the simpl+ files as it says there is "No build task to run found. Configure Build Task ..."

I have looked through everything that I could think of and found nothing I could do. Any help will be helpful.

**Comment by chuget** [comment]
Also I get uncaught Errors under runtime Status
Cannot read properties of undefined (reading 'document')

currently I have 91

**Comment by sentry07** [comment]
When you open VSCode, are you right clicking on a USP file and opening the file directly, or are you right clicking on the folder and opening the folder in VSCode? VSCode's task engine does not work when opening individual files directly.

**Comment by sentry07** [comment]
Since there has been no response, I'm closing this in 4 days.
