### ISSUE TITLE
The term 'x86' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by mdupre95** [sentry07/vscode-crestron-splus#25]
Hi,

I get this error every time I use the "Compile 3&4 Series" task. If I use the Compile task for 3 series or 4 series separately, it works. 

Here's the error detail from the terminal : 
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At line:1 char:20
+ C:\\Program Files (x86)\\Crestron\\SIMPL\\SPlusCC.exe \rebuild c:\Use ...
+                    ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sentry07** [comment]
In the folder that you're working in, check for a tasks.json file and delete it.

**Comment by mdupre95** [comment]
Thanks but I did that already and it did not fix it unfortunately.  What's weird is that it works well when compiling any usp file with either 3 series or 4 series independently but not when when using both together.

**Comment by sentry07** [comment]
Does it happen in other folders?

**Comment by mdupre95** [comment]
Ok, so there was indeed a default task built somehow that caused the issue. The file was buried in the VC code folders in the user directories... I deleted it and now it work.

Thanks for he help and the great job on that extension !
