### ISSUE TITLE
Update to Snippets

### ISSUE THREAD

**Issue by Duck1776** [sentry07/vscode-crestron-splus#26]
[snippets.json](https://github.com/sentry07/vscode-crestron-splus/files/13034437/snippets.json)

I did this for fun. 🦆

**Comment by Duck1776** [comment]
I'm gonna add more stuff today cause I realized I forgot structures. I defined some cues in the snippets and I'll describe them when I update later. 🦆

**Comment by scottpidzarko** [comment]
If you want to propose a change to the repository contents, do it through a Pull Request instead of an issue.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Duck1776** [comment]
Figured it out... :)
