### ISSUE TITLE
[BUG] Build task fails when terminal in VS Code is Powershell

### ISSUE THREAD

**Issue by andrew-welker** [sentry07/vscode-crestron-splus#8]
I use Powershell as my terminal in VS Code. When invoking the build task using ctl-shift-b, I get the following error:
![image](https://user-images.githubusercontent.com/1765622/80559549-12688f80-899b-11ea-9dcd-f23346f59bea.png)

My guess is that this is due to the way the quotes are in the command, but I haven't been able to actually compile directly from the terminal myself yet. Working on that now.

**Comment by andrew-welker** [comment]
I went to Terminal/Configure Default Build Task and added a tasks.json file to a .vscode folder at the root of the folder containing my S+ file. I changed the build command to the following, and it worked. Not sure how to make it happen automatically though.

`"& 'C:\\Program Files (x86)\\Crestron\\SIMPL\\SPlusCC.exe' \\rebuild 'c:\\Users\\awelker\\Documents\\Crestron Cert Exam\\Certification2019\\Routing v1.0.0.usp' \\target series3"`

**Comment by bitm0de** [comment]
Perfect! Thanks Andrew, I might check into this later tomorrow

**Comment by sentry07** [comment]
Fixed with 0.4.2 release. Changed build command back to using 'cmd.exe' as the shell, overriding vscode's default.
