### ISSUE TITLE
[BUG] A new blank line is added to the end of the file

### ISSUE THREAD

**Issue by andrew-welker** [sentry07/vscode-crestron-splus#9]
A new blank line is added to the end of the file on every save, leading to loads of unnecessary blank space at the end of the file. See attached file.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1765622/80560564-a425cc00-899e-11ea-9234-968b0c299c57.gif)

**Comment by sentry07** [comment]
Fixed with 0.4.2 release.
